```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Preperation

## Loading packages 

```{r loading_packages, message=FALSE, warning=FALSE}
library(protti)
library(dplyr)
library(magrittr)
library(ggplot2)
library(stringr)
library(tidyr)
library(reshape2)
library(heatmaply)
```

## Loading data


```{r loading_data, message=FALSE, warning=FALSE}

working_directory = "Z:/jumogl/JM002_LiPSchool/Spectronaut output"
file_name = "20240321_153536_20240320093116_Report.csv"

setwd(working_directory)

DIA_raw <- read_protti(file_name)

mainDir <- working_directory
subDir <- "Plots_Imputation"

if (file.exists(subDir)){
  setwd(file.path(mainDir, subDir))
} else {
  dir.create(file.path(mainDir, subDir))
  setwd(file.path(mainDir, subDir))
  
}

mainDir <- file.path(mainDir, subDir)

DIA_raw$condrep <- paste(DIA_raw$r_condition,DIA_raw$r_replicate, sep = "_")


```

```{r cleaning_data, message=FALSE, warning=FALSE}

subDir <- "QC"

if (file.exists(subDir)){
    setwd(file.path(mainDir, subDir))
} else {
    dir.create(file.path(mainDir, subDir))
    setwd(file.path(mainDir, subDir))
    
}

DIA_raw_norm<- DIA_raw %>%
  filter(eg_is_decoy == FALSE) %>%
  mutate(intensity_log2 = log2(fg_ms2raw_quantity))%>%
  normalise(
    sample = r_file_name,
    intensity_log2 = intensity_log2,
    method = "median"
  ) %>%
  filter(pep_is_proteotypic == TRUE)%>%
  filter(fg_ms2raw_quantity > 32)


plot <- qc_intensity_distribution(
  data = DIA_raw_norm,
  grouping = fg_id,
  intensity = normalised_intensity_log2,
  plot_style = "histogram"
)
plot
ggsave("Intensity_distribution_raw.pdf", plot = plot)





```


```{r LG_imputation_function, message=FALSE, warning=FALSE}
#

impute_MNAR <- function(n_missing, min, sd, rnk){
  	rnorm(n_missing, mean = min - log2(3), sd = sd)[rnk] }

impute_MAR <- function(n_missing, mean, sd, rnk){
	  rnorm(n_missing, mean = mean, sd = sd)[rnk] }

impute_DIA4 <- function(data, r_condition, r_condrep, precursor, intensity){
	data_imputed <- data %>%
	  #select columns condrep, condition, precursor, intensity
		dplyr::select({{r_condrep}}, {{r_condition}}, {{precursor}}, {{intensity}})%>%
	  #fill out missing combinations of precursor values
		tidyr::complete({{precursor}}) %>%
	  #non NA values arranged in descending orderm groups by condrep
		dplyr::arrange(!is.na({{intensity}}), {{r_condrep}}) %>% 
		#calculate mean and standard deviation of intesity within each group (precursor and condition)
	  group_by({{precursor}}, {{r_condition}})%>%
		dplyr::mutate(mean = mean({{intensity}}, na.rm = TRUE)) %>%
		dplyr::mutate(sd = sd({{intensity}}, na.rm = TRUE))%>%
	  #count missing values
		dplyr::mutate(missing = sum(is.na({{intensity}})))%>%
	  #count replicates
		dplyr::mutate(repl = dplyr::n())%>%
	  #enumerator to select select value (ranks within each group)
		dplyr::mutate(rnk = 1:dplyr::n())%>%
	  #calculate minimum intensities per precursor
		group_by({{precursor}})%>%
	  #average across sd's of the conditions for new sd? 
		dplyr::mutate(sd = mean(sd, na.rm = TRUE))%>%
	  #minimum intensity per precursor
		dplyr::mutate(min = min({{intensity}}, na.rm = TRUE))%>%
	  #iterate over rows if intensity is NA imputes - if "all" or one replicate is missing imputes as MNAR, else if one replicate is missing impute MAR, if       not NA takes previous value - changed by me to include MAR definition 
		rowwise() %>%
		dplyr::mutate(normalised_intensity_imputed_log2 = ifelse(is.na({{intensity}}), 	
												ifelse(repl - missing <= 0, impute_MNAR(missing, min, sd, rnk), 
													ifelse(missing == 1, impute_MAR(missing, mean, sd, rnk), {{intensity}})), {{intensity}})) %>%
	  #mark imputed values as such
		dplyr::mutate(imputed = is.na({{intensity}}))%>%
		dplyr::select({{r_condrep}}, {{precursor}}, normalised_intensity_imputed_log2, imputed)%>%
		ungroup()
	#join with imputed data with data
	data %>%
		left_join(data_imputed, by = c(as_label(enquo(r_condrep)), as_label(enquo(precursor))))
}


```

```{r vivi_imputation_function (no MAR imputation), message=FALSE, warning=FALSE}

impute_vivi <- function(data, sample, replicate, grouping, condition, treatment_condition, reference_condition, intensity, cutoff_MAR, cutoff_MNAR, retain_columns = NULL){
  
  data_complete <- data %>% 
    #fitler out data neither in reference or treatment condition    
    filter( {{ condition }} %in% c(treatment_condition, reference_condition)) %>% 
    #remoce duplicates (in case of grouping eg by peptides i guess)
    distinct( {{ grouping }}, {{ condition }}, {{ replicate }}, {{ intensity }} ) %>% 
    #generate NA for missing values (by grouping, condition and replicate)
    complete( {{ grouping }}, {{ condition }},
              {{ replicate }}, fill = list(area = NA))
    
  #Imputing values
  result <- data %>%
    #again filter out conditions not currently looked at
    filter( {{ condition }} %in% c(treatment_condition, reference_condition)) %>%
    #remove duplicates
    distinct({{ condition }}, {{ grouping }}, {{ replicate }}) %>%
    #group by condition and grouping (usually fg_id)
    group_by( {{ condition }},  {{ grouping }}) %>%
    #generate column showing observations per group (excludes na values)
    mutate(n_observations = n()) %>%
    ungroup() %>%
    #calculate missingness: changed to make missingness "neither" as standard and "complete" if all are present 
    mutate(missingness = ifelse(n_observations == length({{replicate}}[!duplicated({{replicate}})]), "complete", "neither")) %>%
    #if observations are below MAR cutoff - classified as MAR, i changed MAR classification to be n_observation == MAR - works but for more replicates would have to be changed to <=  but not complete
    mutate(missingness = ifelse(n_observations == cutoff_MAR, "MAR", missingness)) %>%
    #if observations are less or equal to MNAR cutoff, classified as MNAR
    mutate(missingness = ifelse(n_observations <= cutoff_MNAR, "MNAR", missingness)) %>%
    #make sure distinct list of observations and missingness per condition and grouping (fg_id)
    distinct( {{ condition }},  {{ grouping }}, n_observations, missingness) %>%
    #join to data complete by grouping (fg_id) and condition - introduces na values to be imputed
    right_join(data_complete,
               by = c(rlang::as_name(rlang::enquo(condition)), rlang::as_name(rlang::enquo(grouping)))) %>%
    #na values - observations set to 0 - else set to n_observations
    mutate(n_observations = ifelse(is.na(n_observations), 0, n_observations)) %>%
    #if missingness is na - set to MNAR (values to be imputed)
    mutate(missingness = ifelse(is.na(missingness), "MNAR", missingness)) %>%
    #create comparison column
    mutate(comparison = paste(treatment_condition, "vs", reference_condition, sep = "_")) %>%
    #mutate({{ condition }} = paste( {{ induction }},  {{ condition }}, sep = "_")) %>%
    #add condrep as new_sample_id
    mutate(new_sample_id = paste({{ condition }}, {{ replicate }}, sep = "_")) %>%
    #add imputed label (added by me for plotting)
    mutate(imputed = ifelse(is.na({{ intensity }}), TRUE, FALSE))%>%
    #calculate means, sd's and min by condition and grouping
    group_by( {{ condition }},  {{ grouping }}) %>%
    mutate(mean = mean({{ intensity }}, na.rm = TRUE)) %>%
    mutate(sd = sd({{ intensity }}, na.rm = TRUE)) %>%
    mutate(min = min(mean)) %>%
    ungroup()
  
  #generate unique list of groupings (fg_id) with misisngness = complete
  complete_peptides <- result %>% 
    filter(missingness == "complete") %>% 
    pull({{ grouping }}) %>% 
    unique()
  #generate unique list of groupings with missingness = MNAR and that are not in the list with missingness = complete
  MNAR_peptides_to_remove <- result %>% 
    filter(missingness == "MNAR") %>% 
    filter(!{{ grouping }} %in% complete_peptides) %>% 
    pull({{ grouping }}) %>% 
    unique()
  
  result <- result %>% 
    #filter(!{{ grouping }} %in% MNAR_peptides_to_remove) %>% 
    group_by({{ grouping }}) %>%
    #calculate means, sd's and mins for the created NA values 
    mutate(mean = ifelse(is.na(mean), mean({{ intensity }}, na.rm = TRUE), mean)) %>% 
    mutate(sd = ifelse(is.na(sd), mean(sd, na.rm = TRUE), sd)) %>% 
    mutate(min = ifelse(is.na(min), min(mean), min)) %>% 
    ungroup() %>% 
    #calculate mean for imputation if missingness is MNAR (minimum mean - 3) 
    mutate(mean_calc = ifelse(missingness == "MNAR", min - 3, mean)) %>% 
    group_by(new_sample_id, {{ condition }}, {{ grouping }}, {{ intensity }}, missingness, comparison, imputed) %>% 
    #impute missing values MNAR (min mean - 3 with calc sd)
    do(imputed_intensity = suppressWarnings(rnorm(1, mean = .$mean_calc, sd = .$sd))) %>% 
    #replace NA values with imputed values
    mutate(imputed_intensity = ifelse(is.na({{ intensity }}), imputed_intensity, {{ intensity }})) %>% 
    #filter out rows with intensity = na and missingness either complete or MAR
    filter(!(is.na({{ intensity }}) & missingness %in% c("complete", "MAR","neither"))) %>% 
    #filter out nan values
    filter(!(is.nan(imputed_intensity)))

  if (missing(retain_columns)) {
    #if there is no value for retain_columns, return result
    return(result)
  } else {
    #if retain_columns provided - join result with column from original data
    join_result <- data %>%
      dplyr::ungroup() %>%
      dplyr::select(!!enquo(retain_columns), colnames(result)[!colnames(result) %in% c("imputed_intensity", "missingness", "comparison", "new_sample_id", "imputed")]) %>%
      dplyr::distinct() %>%
      dplyr::right_join(result, by = colnames(result)[!colnames(result) %in% c("imputed_intensity", "missingness", "comparison", "new_sample_id", "imputed")]) %>%
      # Arrange by grouping but in a numeric order of the character vector.
      dplyr::arrange(factor({{ grouping }}, levels = unique(stringr::str_sort({{ grouping }}, numeric = TRUE))))
    
    return(join_result)
  }
  
}

```

```{r intensity_distribution_plotting_imputed, message=FALSE, warning=FALSE}

intensity_distribution_imputed <- function(data,grouping, intensity_log2, imputed) {
  
  plot <- data %>% ggplot2::ggplot(ggplot2::aes(x = {
      {
        intensity_log2
      }
    }, fill = 
      
        {{imputed}}
      
      )) + ggplot2::geom_histogram(binwidth = 0.5, color = "black") + 
      ggplot2::labs(title = "Overall log2 Intensity Distribution", 
      x = "Log2 Intensity", y = "Frequency") + 
      ggplot2::theme_bw() + ggplot2::theme(plot.title = ggplot2::element_text(size = 20), 
      axis.title.x = ggplot2::element_text(size = 15), 
      axis.text.y = ggplot2::element_text(size = 15), 
      axis.text.x = ggplot2::element_text(size = 12), 
      axis.title.y = ggplot2::element_text(size = 15), 
      strip.text = ggplot2::element_text(size = 15), strip.background = element_blank())
    return(plot)
  }


```

```{r imputing_values_LG, message=FALSE, warning=FALSE}

setwd(mainDir)

DIA_raw_prot <- DIA_raw_norm%>%filter(normalised_intensity_log2 > 10) %>% filter(pep_is_proteotypic == TRUE)

#generate NA for missing values
DIA_NA <- DIA_raw_prot %>% 
  filter( r_condition %in% c("Rapa_LiP", "DMSO_LiP")) %>% 
  distinct( fg_id, r_condition, r_replicate, fg_ms2raw_quantity, .keep_all = TRUE ) %>% 
  complete( fg_id, r_condition,
            r_replicate, fill = list(area = NA))


#get missingness for LG df
missingness <- DIA_raw_norm %>% assign_missingness(condrep,
                     r_condition,
                     fg_id,
                     normalised_intensity_log2,
                     ref_condition = "DMSO_LiP",
                     retain_columns = c(pg_protein_accessions, pep_stripped_sequence, eg_qvalue))


#match fg_ids to accessions, peptide sequences and missingness
get_protein_keys <- function(data){
  fg_df <- data %>% distinct(fg_id, .keep_all = TRUE)
  protein_accessions <- data.frame(row.names=c(fg_df$fg_id), val=c(fg_df$pg_protein_accessions))
  return (protein_accessions)
}

get_pep_keys <- function(data){
  fg_df <- data %>% distinct(fg_id, .keep_all = TRUE)
  pep_sequences <- data.frame(row.names=c(fg_df$fg_id), val=c(fg_df$pep_stripped_sequence))
  return (pep_sequences)
}
get_missingness_keys <- function(data){
  fg_df <- data %>% distinct(fg_id, .keep_all = TRUE)
  miss <- data.frame(row.names=c(fg_df$fg_id), val=c(fg_df$missingness))
  return (miss)
}


protein_keys <- get_protein_keys(DIA_raw)
pep_keys <- get_pep_keys(DIA_raw)
missingness_key <-  get_missingness_keys(missingness)


DIA_NA$pep_stripped_sequence[is.na(DIA_NA$pep_stripped_sequence)] <- pep_keys[DIA_NA$fg_id[is.na(DIA_NA$pep_stripped_sequence)],]
DIA_NA$pg_protein_accessions[is.na(DIA_NA$pg_protein_accessions)] <- protein_keys[DIA_NA$fg_id[is.na(DIA_NA$pg_protein_accessions)],]
DIA_NA$missingness <- missingness_key[DIA_NA$fg_id,]

#add condrep
DIA_NA$condrep <- paste(DIA_NA$r_condition, DIA_NA$r_replicate, sep = "_")

plot <- qc_intensity_distribution(
  data = DIA_raw_norm,
  grouping = fg_id,
  intensity = normalised_intensity_log2,
  plot_style = "histogram"
)
plot
ggsave("Intensity_distribution_raw.pdf", plot = plot)
set.seed(123)
LG_imputed <- impute_DIA4(data = DIA_NA, r_condition = r_condition, r_condrep = condrep, precursor = fg_id, intensity = normalised_intensity_log2)



plot <- intensity_distribution_imputed(
  data = LG_imputed,
  grouping = fg_id,
  intensity_log2 = normalised_intensity_imputed_log2,
  imputed = imputed
)
plot
ggsave("Intensity_distribution_LG_imputed.pdf", plot = plot)

```


```{r imputing_values_vivi, message=FALSE, warning=FALSE}

setwd(mainDir)

DIA_raw_prot <- DIA_raw_norm%>%filter(normalised_intensity_log2 > 10) %>% filter(pep_is_proteotypic == TRUE)
set.seed(123)
vivi_imputed <- impute_vivi(data = DIA_raw_prot, sample = r_file_name, replicate = r_replicate, grouping = fg_id, condition = r_condition, treatment_condition = "Rapa_LiP", reference_condition = "DMSO_LiP", intensity = normalised_intensity_log2, cutoff_MAR = 3, cutoff_MNAR = 1, retain_columns = c("pep_is_proteotypic", "r_file_name")) %>% left_join(DIA_raw %>% distinct(pg_protein_accessions, pep_stripped_sequence, fg_id), 
              by = c("fg_id"), relationship = "many-to-many")



vivi_imputed$condrep <- vivi_imputed$new_sample_id


plot <- intensity_distribution_imputed(
  data = vivi_imputed,
  grouping = fg_id,
  intensity = imputed_intensity,
  imputed = imputed
)

plot
ggsave("Intensity_distribution_vivi_imputed.pdf", plot = plot)


```


## Volcano plots precurser lvl


```{r Volcano_plot_LG, message = FALSE, warning = FALSE}


subDir <- "Volcano's"

if (file.exists(subDir)){
    setwd(file.path(mainDir, subDir))
} else {
    dir.create(file.path(mainDir, subDir))
    setwd(file.path(mainDir, subDir))
    
}


Volcano_input <- LG_imputed %>%
  unique() %>%
  assign_missingness(condrep,
                     r_condition,
                     fg_id,
                     normalised_intensity_imputed_log2,
                     ref_condition = "DMSO_LiP",
                     retain_columns = c(pg_protein_accessions, pep_stripped_sequence))


t_test_result_pre <- calculate_diff_abundance(data = Volcano_input,
                                condrep,
                                r_condition,
                                fg_id,
                                normalised_intensity_imputed_log2,
                                missingness,
                                comparison = comparison,
                                ref_condition = "DMSO_LiP",
                                method = "moderated_t-test",
                                retain_columns = c(pg_protein_accessions, pep_stripped_sequence))





condition_vulcano <- c("Rapa_LiP_vs_DMSO_LiP")
t_test_result_proDA_pep_comp <- t_test_result_pre[t_test_result_pre$comparison %in% condition_vulcano, ]


plot <- volcano_plot(t_test_result_proDA_pep_comp, fg_id, diff, adj_pval, method = "target", target_column = pg_protein_accessions, target = c("P62942") ,  x_axis_label = "log2(fold change) ", title = "Volcano plot peptide level", y_axis_label = "-log10(p-value)", log2FC_cutoff = 1, significance_cutoff = 0.01, interactive = F)

plot
ggsave("volcano_plot_LG_imputed.png", plot = plot)
#volcano_plot(t_test_result_proDA_pep_comp, pep_grouping_key, diff, adj_pval, method = "target", target_column = pg_protein_accessions, target = c("P24941") ,  x_axis_label = "log2(fold change)", title = "Volcano plot precursor level", y_axis_label = "-log10(q-value)", log2FC_cutoff = 1, significance_cutoff = 0.05, interactive = T)


pep_hits_LG <- subset(t_test_result_proDA_pep_comp, adj_pval < 0.01 & (diff < -1 | diff > 1))
protein_hits_LG <- pep_hits_LG$pg_protein_accessions[!duplicated(pep_hits_LG$pg_protein_accessions)]



```


```{r Volcano_plot_vivi, message = FALSE, warning = FALSE}


subDir <- "Volcano's"

if (file.exists(subDir)){
    setwd(file.path(mainDir, subDir))
} else {
    dir.create(file.path(mainDir, subDir))
    setwd(file.path(mainDir, subDir))
    
}


Volcano_input <- vivi_imputed_norm %>%
  unique() %>%
  assign_missingness(condrep,
                     r_condition,
                     fg_id,
                     normalised_intensity_log2,
                     ref_condition = "DMSO_LiP",
                     retain_columns = c(pg_protein_accessions, pep_stripped_sequence))


t_test_result_pre <- calculate_diff_abundance(data = Volcano_input,
                                condrep,
                                r_condition,
                                fg_id,
                                normalised_intensity_log2,
                                missingness,
                                comparison = comparison,
                                ref_condition = "DMSO_LiP",
                                method = "moderated_t-test",
                                retain_columns = c(pg_protein_accessions, pep_stripped_sequence))





condition_vulcano <- c("Rapa_LiP_vs_DMSO_LiP")
t_test_result_proDA_pep_comp <- t_test_result_pre[t_test_result_pre$comparison %in% condition_vulcano, ]


plot <- volcano_plot(t_test_result_proDA_pep_comp, fg_id, diff, adj_pval, method = "target", target_column = pg_protein_accessions, target = c("P62942") ,  x_axis_label = "log2(fold change) ", title = "Volcano plot peptide level", y_axis_label = "-log10(p-value)", log2FC_cutoff = 1, significance_cutoff = 0.01, interactive = F)

plot
ggsave("volcano_plot_vivi_imputed.png", plot = plot)
#volcano_plot(t_test_result_proDA_pep_comp, pep_grouping_key, diff, adj_pval, method = "target", target_column = pg_protein_accessions, target = c("P24941") ,  x_axis_label = "log2(fold change)", title = "Volcano plot precursor level", y_axis_label = "-log10(q-value)", log2FC_cutoff = 1, significance_cutoff = 0.05, interactive = T)


pep_hits_vivi <- subset(t_test_result_proDA_pep_comp, adj_pval < 0.01 & (diff < -1 | diff > 1))
protein_hits_vivi <- pep_hits_vivi$pg_protein_accessions[!duplicated(pep_hits_vivi$pg_protein_accessions)]



```

```{r intensity across conditions profile plot as function, message=FALSE, warning=FALSE}
#columns of data as variables not working for some reason
profile_plot <- function(data, hits,dataset = "", intensity_log2 = "normalised_intensity_log2"){
  #generate subset and group by stripped sequence and condition
  for (p in 1:length(hits)){
    subs <- subset(data, pg_protein_accessions == hits[p])
    subs <-  arrange(subs,pep_stripped_sequence, r_condition)
    
    #get unique set of conditions and pep_stripped_sequences
    conditions <- subs$condrep[!duplicated(subs$condrep)]
    conditions <- str_sort(conditions)
    sequences <- subs$pep_stripped_sequence[!duplicated(subs$pep_stripped_sequence)]
    
    
    #generate matrix of zeros for the intensities
    df <- data.frame()
    for (i in 1:length(conditions)){
      column = numeric(length(sequences))
      df = rbind(df, column)
    }
    
    colnames(df)<-sequences
    rownames(df)<-conditions
    df$condrep = conditions
    #return(df)
    #fill in data
    #iterate over conditions
    for (i in 1:length(conditions)){
      #iterate over sequences
      for (j in 1:length(sequences)){
        #generate sub-subset containing only values for given condition and sequence (single value or list of duplicates)
        x <- subset(subs, pep_stripped_sequence == sequences[j] & condrep == conditions[i])
        #eliminate duplicate values and save in dataframe while adding up all fragments of peptide 
         value <- log2(sum(2^(x$intensity_log2[!duplicated(x$intensity_log2)])))
         #fix if there are no values - doesn't try to overwrite zero with empty value
        if (length(value) > 0){
          df[i,j] <- value
        }
      }
    }
    df_m <- melt(df)
    
    #sizing constant depending on size of legend
    aspect = length(sequences)%/%15 * 0.35 + 0.65
    plot <- ggplot(df, aes(condrep)) +
      geom_line(data = df_m, aes(x=condrep, y=value, group = variable, colour = variable))+
      scale_x_discrete(guide = guide_axis(angle = 90))+
      xlab("Condition")+
      ylab("Normalised Log2 Intensity")+
      theme(legend.key.size = unit(0.832, "lines"))+
      geom_point(data = df_m, aes(condrep, value))+
      ggtitle(hits[p])
    ggsave(filename = paste(dataset,paste(hits[p], "profile_plot.png", sep = "_"),sep=""), height = 5, width = 7 * aspect,  plot = plot)
  }
}

```

```{r intensity across conditions profile plot vivi, message=FALSE, warning=FALSE}
subDir <- "Vivi_profiles"

if (file.exists(subDir)){
    setwd(file.path(mainDir, subDir))
} else {
    dir.create(file.path(mainDir, subDir))
    setwd(file.path(mainDir, subDir))
    
}

profile_plot(vivi_imputed_norm, dataset = "vivi_",hits = protein_hits_vivi)



```

```{r intensity across conditions profile plot LG, message=FALSE, warning=FALSE}
subDir <- "LG_profiles"

if (file.exists(subDir)){
    setwd(file.path(mainDir, subDir))
} else {
    dir.create(file.path(mainDir, subDir))
    setwd(file.path(mainDir, subDir))
    
}

profile_plot(LG_imputed, dataset = "LG_",hits = protein_hits_LG,intensity_log2 = "normalised_intensity_imputed_log2" )




```

```{r missingness as function of intesity, message=FALSE, warning=FALSE}

subDir <- "main plots"

if (file.exists(subDir)){
    setwd(file.path(mainDir, subDir))
} else {
    dir.create(file.path(mainDir, subDir))
    setwd(file.path(mainDir, subDir))
    
}

#missingness for clean data
missingness <- DIA_raw_norm %>% assign_missingness(condrep,
                     r_condition,
                     fg_id,
                     normalised_intensity_log2,
                     ref_condition = "DMSO_LiP",
                     retain_columns = c(pg_protein_accessions, pep_stripped_sequence, eg_qvalue))

missingness$missingness[is.na(missingness$missingness)] <- "neither"

png(file ="boxplot_missingness_vs_intensity_clean.png")
plot <- boxplot(normalised_intensity_log2~missingness, data = missingness, ylim= c(5,25)) 
title("missingness vs intensity")
#ggsave(filename = "boxplot_missingness_vs_intensity.png",  plot = plot)
plot
dev.off()

png(file ="boxplot_missingness_vs_eg_qvalue_clean.png")
plot <- boxplot(eg_qvalue~missingness, data = missingness, ylim = c(0, 0.00015)) 
title("missingness vs eg_qvalue")
#ggsave(filename = "boxplot_missingness_vs_intensity.png",  plot = plot)
plot
dev.off()

#assign missingness to raw data
missingness_raw <- DIA_raw %>% assign_missingness(condrep,
                     r_condition,
                     fg_id,
                     fg_ms2raw_quantity,
                     ref_condition = "DMSO_LiP",
                     retain_columns = c(pg_protein_accessions, pep_stripped_sequence, eg_qvalue, eg_is_decoy, pep_is_proteotypic))

missingness_raw$missingness[is.na(missingness_raw$missingness)] <- "neither"

missingness_raw<- missingness_raw %>%
  filter(eg_is_decoy == FALSE) %>%
  mutate(intensity_log2 = log2(fg_ms2raw_quantity))%>%
  filter(pep_is_proteotypic == TRUE)


png(file ="boxplot_missingness_vs_intensity_raw.png")
plot <- boxplot(intensity_log2~missingness, data = missingness_raw, ylim= c(5,25)) 
title("missingness vs intensity")
#ggsave(filename = "boxplot_missingness_vs_intensity.png",  plot = plot)
plot
dev.off()

png(file ="boxplot_missingness_vs_eg_qvalue_raw.png")
plot <- boxplot(eg_qvalue~missingness, data = missingness_raw, ylim = c(0, 0.00015)) 
title("missingness vs eg_qvalue")
#ggsave(filename = "boxplot_missingness_vs_intensity.png",  plot = plot)
plot
dev.off()

```
```{r data completeness, message=FALSE, warning=FALSE}

subDir <- "main plots"

if (file.exists(subDir)){
    setwd(file.path(mainDir, subDir))
} else {
    dir.create(file.path(mainDir, subDir))
    setwd(file.path(mainDir, subDir))
    
}

plot <- qc_data_completeness(
  data = DIA_raw,
  sample = r_file_name,
  grouping = fg_id,
  intensity = fg_ms2raw_quantity,
  plot = TRUE
)

ggsave(filename = "data_completeness.png", plot = plot)

plot



```

```{r data completeness, message=FALSE, warning=FALSE}

heatmaply(missingness,
          xlab = "condrep",
          ylab = "missingness")

```

