```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Preperation

## Loading packages 

```{r loading_packages, message=FALSE, warning=FALSE}
library(protti)
library(dplyr)
library(magrittr)
library(ggplot2)

```

## Loading data


```{r loading_data, message=FALSE, warning=FALSE}

working_directory = "Z:/jumogl/JM003_AT222/spectronaut output"
file_name = "20240411_162202_20240407072240_Report_Eclipse_MD.csv"

setwd(working_directory)

DIA_raw <- read_protti(file_name)

mainDir <- working_directory
subDir <- paste("Plots", file_name) 

if (file.exists(subDir)){
    setwd(file.path(mainDir, subDir))
} else {
    dir.create(file.path(mainDir, subDir))
    setwd(file.path(mainDir, subDir))
    
}

mainDir <- file.path(mainDir, subDir)
```


```{r cleaning_data, message=FALSE, warning=FALSE}
#why not fg_quantity as on protti page? 
subDir <- "dose_response_analysis_plots"

if (file.exists(subDir)){
    setwd(file.path(mainDir, subDir))
} else {
    dir.create(file.path(mainDir, subDir))
    setwd(file.path(mainDir, subDir))
    
}

DIA_raw_norm<- DIA_raw %>%
  filter(eg_is_decoy == FALSE) %>%
  mutate(intensity_log2 = log2(fg_ms2raw_quantity))%>%
  normalise(
    sample = r_file_name,
    intensity_log2 = intensity_log2,
    method = "median"
  ) %>%
  filter(pep_is_proteotypic == TRUE)

plot <- qc_intensity_distribution(
  data = DIA_raw_norm,
  grouping = fg_id,
  intensity = normalised_intensity_log2,
  plot_style = "histogram"
)
plot
ggsave("Intensity_distribution_raw.pdf", plot = plot)

DIA_raw_norm <- DIA_raw_norm %>%
  filter(normalised_intensity_log2 > 5)

plot <- qc_intensity_distribution(
  data = DIA_raw_norm,
  grouping = fg_id,
  intensity = normalised_intensity_log2,
  plot_style = "histogram"
)
plot
ggsave("Intensity_distribution_clean.pdf", plot = plot)



```



```{r clustering_of_samples, message=FALSE, warning=FALSE}
setwd(file.path(mainDir, subDir))

#doesn't work :(

plot <- qc_sample_correlation(
  data = DIA_raw_norm,
  sample = r_file_name,
  grouping = fg_id,
  intensity_log2 = normalised_intensity_log2,
  condition = r_condition
)
plot
ggsave("sample_correlation.pdf", plot = plot)

plot <- qc_pca(
  data = DIA_raw_norm,
  sample = r_file_name,
  grouping = fg_id,
  intensity = normalised_intensity_log2,
  condition = r_condition
)
plot
ggsave("PCA.pdf", plot = plot)

```




```{r fitting_dose-response_curve, message=FALSE, warning=FALSE}

DIA_raw_norm$conc_frag <- as.numeric(gsub("_mM", "", DIA_raw_norm$r_condition))
#subs <- subset(DIA_raw_norm,pg_protein_accessions == 	"A0AVT1")
future::plan(future::multisession, workers = 4)
fit  <- DIA_raw_norm %>%
  parallel_fit_drc_4p(
    sample = r_file_name,
    grouping = fg_id,
    response = normalised_intensity_log2,
    dose = conc_frag,
    filter = "post",
    retain_columns = c(pg_protein_accessions),
    replicate_completeness = 0.7,
    condition_completeness =0.5,
    correlation_cutoff = 0.8,
    log_logarithmic = TRUE,
    n_cores = 4
  )  

future::plan(future::sequential)
```

```{r model_fit_plotting, message=FALSE, warning=FALSE}

setwd(file.path(mainDir, subDir))

#generate vector of all hits to use for plotting
ranks <- fit$rank
ranks <- ranks[!is.na(ranks)]
hits <- fit$fg_id[1:length(ranks)]

one <- hits[1]
#plot dose response curve for each hit iteratively
for (i in 1:length(hits)){
  plot <- drc_4p_plot(fit,
    grouping = fg_id,
    dose = conc_frag,
    response = normalised_intensity_log2,
    targets = hits[i],
    unit = "mM",
    export = TRUE,
    export_name = paste(hits[i],"dose_response", sep = "_")
  )
  plot
}
```


